language: node_js
sudo: false
node_js:
  - 4
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
  - npm install -g bower browserify
  - bower install
  - npm install
  - export PATH=$PWD/node_modules/.bin:$PATH
  - npm run build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - xvfb-run testling -x firefox
  - xvfb-run testling -x google-chrome

