language: node_js
sudo: false
node_js:
  - 4
addons:
  firefox: latest
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
  - npm install -g bower browserify
  - bower install
  - npm install
  - export PATH=$PWD/node_modules/.bin:$PATH
  - npm run build
  - 'export DISPLAY=:99.0'
script:
  - xvfb-run testling -x firefox
